service: jungyeon-api-test

provider:
  name: aws
  stage: dev
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
#custom:
#  pythonRequirements:
#    dockerizePip: true
#    useDownloadCache: false
#    useStaticCache: false

#plugins:
#  - serverless-python-requirements

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

  create:
    handler: create.create
    events:
      - http:
          path: /
          method: post

  delete:
    handler: delete.delete
    events:
      - http:
          path: /{postId}
          method: delete

  update:
    handler: update.update
    events:
      - http:
          path: /{postId}
          method: put
